import comp from "C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/vue/vue3.html.vue"
const data = JSON.parse("{\"path\":\"/posts/vue/vue3.html\",\"title\":\"Vue3\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2022-01-01T00:00:00.000Z\",\"order\":1,\"sticky\":100,\"category\":[\"前端开发\"],\"tag\":[\"Vue3\",\"前端开发\"],\"description\":\"Vue3 1.Vue3简介 2020年9月18日，Vue.js发布版3.0版本，代号：One Piece（n 经历了：4800+次提交、40+个RFC、600+次PR、300+贡献者 官方发版地址：Release v3.0.0 One Piece · vuejs/core 截止2023年10月，最新的公开版本为：3.3.4 1.1Vue3的优势 （1）...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Vue3\\\",\\\"image\\\":[\\\"http://49.232.112.44/images/default_slot.png\\\"],\\\"datePublished\\\":\\\"2022-01-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"reveal\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/test/posts/vue/vue3.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"reveal\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Vue3\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Vue3 1.Vue3简介 2020年9月18日，Vue.js发布版3.0版本，代号：One Piece（n 经历了：4800+次提交、40+个RFC、600+次PR、300+贡献者 官方发版地址：Release v3.0.0 One Piece · vuejs/core 截止2023年10月，最新的公开版本为：3.3.4 1.1Vue3的优势 （1）...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://49.232.112.44/images/default_slot.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"前端开发\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue3\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-01T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":40.85,\"words\":12254},\"filePathRelative\":\"posts/vue/vue3.md\",\"excerpt\":\"\\n<h2>1.Vue3简介</h2>\\n<ul>\\n<li>2020年9月18日，<code>Vue.js</code>发布版<code>3.0</code>版本，代号：<code>One Piece</code>（n</li>\\n<li>经历了：<a href=\\\"https://github.com/vuejs/core/commits/main\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">4800+次提交</a>、<a href=\\\"https://github.com/vuejs/rfcs/tree/master/active-rfcs\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">40+个RFC</a>、<a href=\\\"https://github.com/vuejs/vue-next/pulls?q=is%3Apr+is%3Amerged+-author%3Aapp%2Fdependabot-preview+\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">600+次PR</a>、<a href=\\\"https://github.com/vuejs/core/graphs/contributors\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">300+贡献者</a></li>\\n<li>官方发版地址：<a href=\\\"https://github.com/vuejs/core/releases/tag/v3.0.0\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Release v3.0.0 One Piece · vuejs/core</a></li>\\n<li>截止2023年10月，最新的公开版本为：<code>3.3.4</code></li>\\n</ul>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
