export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/intro.html.js"), meta: {"cover":"/assets/images/cover3.jpg","excerpt":"\n<p>将你的个人介绍和档案放置在此处。</p>\n","readingTime":{"minutes":0.08,"words":23},"title":"介绍页","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"主页","icon":"house"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/demo/disable.html.js"), meta: {"category":["使用指南"],"tag":["禁用"],"sticky":-6,"excerpt":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","readingTime":{"minutes":0.43,"words":130},"title":"布局与功能禁用","icon":"gears","order":4,"type":"article"} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/demo/encrypt.html.js"), meta: {"category":["使用指南"],"tag":["加密"],"sticky":-5,"isEncrypted":true,"readingTime":{"minutes":0.52,"words":156},"title":"密码加密的文章","icon":"lock","type":"article"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/demo/layout.html.js"), meta: {"category":["指南"],"tag":["布局"],"sticky":-4,"excerpt":"<p>布局包括:</p>\n<ul>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/navbar.html\" target=\"_blank\" rel=\"noopener noreferrer\">导航栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/sidebar.html\" target=\"_blank\" rel=\"noopener noreferrer\">侧边栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/footer.html\" target=\"_blank\" rel=\"noopener noreferrer\">页脚</a></li>\n</ul>","readingTime":{"minutes":0.54,"words":161},"title":"布局","icon":"object-group","order":2,"type":"article"} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/demo/markdown.html.js"), meta: {"category":["使用指南"],"tag":["Markdown"],"sticky":-3,"excerpt":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你需要创建并编写 Markdown，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","readingTime":{"minutes":3.48,"words":1043},"title":"Markdown 展示","icon":"fa6-brands:markdown","order":2,"type":"article"} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/demo/page.html.js"), meta: {"author":"Ms.reveal","date":1577836800000,"category":["使用指南"],"tag":["页面配置","使用指南"],"sticky":-2,"excerpt":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","readingTime":{"minutes":1.77,"words":531},"title":"页面配置","icon":"file","order":3,"type":"article"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/demo/index.html.js"), meta: {"category":["使用指南"],"sticky":-1,"readingTime":{"minutes":0.07,"words":22},"title":"主要功能与配置演示","icon":"laptop-code","type":"article"} }],
  ["/posts/dev_laguage/1.html", { loader: () => import(/* webpackChunkName: "posts_dev_laguage_1.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/dev_laguage/1.html.js"), meta: {"date":1640995200000,"sticky":99,"excerpt":"\n<p>1.typescript 是微软开发的一款开源编程语言，支持 ECMAScript 6 标准；<br>\n2.TypeScript 是 JavaScript 的超集，这意味着他支持所有的 JavaScript 语法。并在此之上对 JavaScript 添加了一些扩展，如 class / interface / module 等。这样会大大提升代码的可阅读性。<br>\n3.最新的 Vue 、React 也可以集成 TypeScript</p>\n<h1>JavaScript 与 TypeScript 的区别</h1>\n<p>TypeScript 是 JavaScript 的超集，扩展了 JavaScript 的语法，因此现有的 JavaScript 代码可与 TypeScript 一起工作无需任何修改，TypeScript 通过类型注解提供编译时的静态类型检查。</p>","readingTime":{"minutes":2.44,"words":732},"title":"TypeScript 介绍","icon":"pen-to-square","type":"article"} }],
  ["/posts/mapbox/1.html", { loader: () => import(/* webpackChunkName: "posts_mapbox_1.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/mapbox/1.html.js"), meta: {"date":1640995200000,"category":["Mapbox"],"tag":["Mapbox","前端开发"],"sticky":98,"excerpt":"\n<h2>点、线、面</h2>\n<p>添加数据线，收集线数据，type:linestring</p>\n<p>var geojson={<br>\n\"type\":'featurecollection',<br>\n\"feature\":[{<br>\n\"type\": \"Feature\",<br>\n\"geometry\": {<br>\n\"type\": \"LineString\",<br>\n\"coordinates\": []<br>\n}]<br>\n}<br>\n添加线的类型应该设置为：type: LineString，添加相对应坐标 ，配置样式layout和pain：</p>\n<p>layout :{<br>\nline-cap //线显示的类型，可以是圆形、正方形、Butt<br>\nline-join //连接时线的显示<br>\nvisibility // 图层显示与否 none,visible<br>\n}<br>\npain:{<br>\nline-color //线的颜色<br>\nline-width //线的宽度<br>\nline-opacity //线的透明度<br>\nline-translate //线的的偏移量<br>\n}<br>\n给地图添加监听事件：</p>","readingTime":{"minutes":6.76,"words":2028},"title":"Mapbox API","icon":"pen-to-square","type":"article"} }],
  ["/posts/node/1.html", { loader: () => import(/* webpackChunkName: "posts_node_1.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/node/1.html.js"), meta: {"title":"","type":"article"} }],
  ["/posts/vue/vue2.html", { loader: () => import(/* webpackChunkName: "posts_vue_vue2.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/vue/vue2.html.js"), meta: {"title":"Vue2","icon":"pen-to-square","index":false} }],
  ["/posts/vue/vue3.html", { loader: () => import(/* webpackChunkName: "posts_vue_vue3.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/vue/vue3.html.js"), meta: {"date":1640995200000,"category":["前端开发"],"tag":["Vue3","前端开发"],"sticky":100,"excerpt":"\n<h2>1.Vue3简介</h2>\n<ul>\n<li>2020年9月18日，<code>Vue.js</code>发布版<code>3.0</code>版本，代号：<code>One Piece</code>（n</li>\n<li>经历了：<a href=\"https://github.com/vuejs/core/commits/main\" target=\"_blank\" rel=\"noopener noreferrer\">4800+次提交</a>、<a href=\"https://github.com/vuejs/rfcs/tree/master/active-rfcs\" target=\"_blank\" rel=\"noopener noreferrer\">40+个RFC</a>、<a href=\"https://github.com/vuejs/vue-next/pulls?q=is%3Apr+is%3Amerged+-author%3Aapp%2Fdependabot-preview+\" target=\"_blank\" rel=\"noopener noreferrer\">600+次PR</a>、<a href=\"https://github.com/vuejs/core/graphs/contributors\" target=\"_blank\" rel=\"noopener noreferrer\">300+贡献者</a></li>\n<li>官方发版地址：<a href=\"https://github.com/vuejs/core/releases/tag/v3.0.0\" target=\"_blank\" rel=\"noopener noreferrer\">Release v3.0.0 One Piece · vuejs/core</a></li>\n<li>截止2023年10月，最新的公开版本为：<code>3.3.4</code></li>\n</ul>","readingTime":{"minutes":40.85,"words":12254},"title":"Vue3","icon":"pen-to-square","order":1,"type":"article"} }],
  ["/posts/vue_note/1.html", { loader: () => import(/* webpackChunkName: "posts_vue_note_1.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/vue_note/1.html.js"), meta: {"title":"","type":"article"} }],
  ["/posts/website/1.html", { loader: () => import(/* webpackChunkName: "posts_website_1.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/website/1.html.js"), meta: {"title":"学习网站","icon":"pen-to-square","index":false} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/posts/dev_laguage/", { loader: () => import(/* webpackChunkName: "posts_dev_laguage_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/dev_laguage/index.html.js"), meta: {"title":"Dev Laguage"} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"title":"Posts"} }],
  ["/posts/mapbox/", { loader: () => import(/* webpackChunkName: "posts_mapbox_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/mapbox/index.html.js"), meta: {"title":"Mapbox"} }],
  ["/posts/node/", { loader: () => import(/* webpackChunkName: "posts_node_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/node/index.html.js"), meta: {"title":"Node"} }],
  ["/posts/vue/", { loader: () => import(/* webpackChunkName: "posts_vue_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/vue/index.html.js"), meta: {"title":"Vue"} }],
  ["/posts/vue_note/", { loader: () => import(/* webpackChunkName: "posts_vue_note_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/vue_note/index.html.js"), meta: {"title":"Vue Note"} }],
  ["/posts/website/", { loader: () => import(/* webpackChunkName: "posts_website_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/posts/website/index.html.js"), meta: {"title":"Website"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_使用指南_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/category/使用指南/index.html.js"), meta: {"title":"使用指南 分类","index":false} }],
  ["/category/%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_指南_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/category/指南/index.html.js"), meta: {"title":"指南 分类","index":false} }],
  ["/category/mapbox/", { loader: () => import(/* webpackChunkName: "category_mapbox_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/category/mapbox/index.html.js"), meta: {"title":"Mapbox 分类","index":false} }],
  ["/category/%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91/", { loader: () => import(/* webpackChunkName: "category_前端开发_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/category/前端开发/index.html.js"), meta: {"title":"前端开发 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/%E7%A6%81%E7%94%A8/", { loader: () => import(/* webpackChunkName: "tag_禁用_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/禁用/index.html.js"), meta: {"title":"标签: 禁用","index":false} }],
  ["/tag/%E5%8A%A0%E5%AF%86/", { loader: () => import(/* webpackChunkName: "tag_加密_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/加密/index.html.js"), meta: {"title":"标签: 加密","index":false} }],
  ["/tag/%E5%B8%83%E5%B1%80/", { loader: () => import(/* webpackChunkName: "tag_布局_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/布局/index.html.js"), meta: {"title":"标签: 布局","index":false} }],
  ["/tag/markdown/", { loader: () => import(/* webpackChunkName: "tag_markdown_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/markdown/index.html.js"), meta: {"title":"标签: Markdown","index":false} }],
  ["/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/", { loader: () => import(/* webpackChunkName: "tag_页面配置_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/页面配置/index.html.js"), meta: {"title":"标签: 页面配置","index":false} }],
  ["/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "tag_使用指南_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/使用指南/index.html.js"), meta: {"title":"标签: 使用指南","index":false} }],
  ["/tag/mapbox/", { loader: () => import(/* webpackChunkName: "tag_mapbox_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/mapbox/index.html.js"), meta: {"title":"标签: Mapbox","index":false} }],
  ["/tag/%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91/", { loader: () => import(/* webpackChunkName: "tag_前端开发_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/前端开发/index.html.js"), meta: {"title":"标签: 前端开发","index":false} }],
  ["/tag/vue3/", { loader: () => import(/* webpackChunkName: "tag_vue3_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/tag/vue3/index.html.js"), meta: {"title":"标签: Vue3","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"C:/Users/slr/Desktop/Vue3学习资料/Vue3_test/11/test/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
